# Generated by Django 6.0.3 on 2026-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=100)),
                ('specialites', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=200)),
                ('est_actif', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('datedecreation', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='traiteurs/')),
            ],
        ),
    ]
