# Generated by Django 6.0.3 on 2026-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traiteur',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
