# Generated by Django 6.0.3 on 2026-04-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_traiteur_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traiteur',
            name='url',
        ),
    ]
